language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
script:
  - npm run test && npm run build
after_success:
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
